custom_graphics_erp/custom_graphics_erp/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView
from django.contrib import admin
from custom_graphics_erp import settings


urlpatterns = patterns('',
   # Examples:
  (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
   url(r'^archive/$', 'office.views.archive', name='archive'),
   url(r'^$', 'office.views.home', name='home'),
   url(r'^quotation/(?P<id>\d+)/$', 'office.views.quotation_manager', name="quotation"),
   # url(r'^quotation/$', 'office.views.quotation_list', name="quotation-list"),
   url(r'^quotation/(?P<id>\d+)/offer/pdf/test/$', 'office.views.myview_test', name="view_pdf_test"),

   url(r'^quotation/(?P<id>\d+)/offer/pdf/$', 'office.views.myview', name="view_pdf"),
   url(r'^add-company-category/$', 'office.views.add_category', name="add-category"),

   # url(r'^quotation/(?P<id>\d+)/offer/$', 'office.views.offer', name="offer"),
   url(r'^management/(?P<id>\d+)/office/$', 'office.views.office', name="office"),
   url(r'^save/send/quotation/(?P<id>\d+)/$', 'office.views.save_send_json', name="save-sand-quotation-json"),
   url(r'^save/quotation/(?P<id>\d+)/$', 'office.views.save_json', name="save-quotation-json"),
   url(r'^admin/', include(admin.site.urls)),
   url(r'^accounts/',
       include('registration.backends.simple.urls')),
   url(r'^login/$', 'office.views.custom_login', name='login'),
   url(r'^logout/$', 'office.views.logout_view', name='logout'),
   url(r'^sales/$', 'office.views.sales', name='sales'),
   url(r'^sales/(?P<id>\d+)/$', 'office.views.sales_details', name='sales-details'),
   url(r'^management/$', 'office.views.management', name='management'),
   # url(r'^quotation-manager/(?P<id>\d+)/$', 'office.views.quotation_manager'),
   url(r'^add-request/$', 'office.views.add_request', name='add-request'),
   url(r'^graphics/$', 'office.views.graphics_list', name='graphics-list'),
   url(r'^production/$', 'office.views.production_list', name='production-list'),
   url(r'^installation/$', 'office.views.installation_list', name='installation-list'),
   url(r'^graphics/(?P<id>\d+)/$', 'office.views.order_graphics', name='graphics-request'),
   url(r'^production/(?P<id>\d+)/$', 'office.views.order_production', name='production-request'),
   url(r'^installation/(?P<id>\d+)/$', 'office.views.order_installation', name='installation-request'),

   url(r'^get_contact_list/$', 'office.views.get_contact_person_list'),
   url(r'^get_date_range/(?P<id>\d+)/$', 'office.views.get_date_range'),
   url(r'^update_status/(?P<id>\d+)/$', 'office.views.update_status', name='update-status'),
   url(r'^archive/new-costumer/$', 'office.views.new_costumer', name='new-costumer'),
   url(r'^archive/customer-card/(?P<id>\d+)/pdf/$', 'office.views.costumer_card_pdf', name='customer-card-pdf'),

   url(r'^archive/customer-card/(?P<id>\d+)/$', 'office.views.customer_card', name='customer-card'),

   url(r'^archive/customer-card/(?P<id>\d+)/add-person/$', 'office.views.add_person', name='add-person'),

   # HTML url's
   # url(r'^signin$', TemplateView.as_view(template_name='sign/signin.html')),
    # url(r'^sales$', TemplateView.as_view(template_name='sales/sales-index.html')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),




   url(r'^recovery$', TemplateView.as_view(template_name='sign/recovery.html')),
   url(r'^recovery-mail$', TemplateView.as_view(template_name='sign/recovery-mail.html')),
   url(r'^new-password$', TemplateView.as_view(template_name='sign/new-password.html')),
   url(r'^broken-link$', TemplateView.as_view(template_name='sign/broken-link.html')),
   url(r'^add-request$', TemplateView.as_view(template_name='sales/new-request.html')),
   url(r'^quotation$', TemplateView.as_view(template_name='management/quotation.html')),
   url(r'^request-details', TemplateView.as_view(template_name='sales/request_details.html')),
   url(r'^orders-list', TemplateView.as_view(template_name='management/orders-list.html')),
   url(r'^customers', TemplateView.as_view(template_name='database/customers.html')),
   url(r'^new-customer', TemplateView.as_view(template_name='database/new-customer.html')),
   url(r'^orders-full', TemplateView.as_view(template_name='management/order-full.html')),
   url(r'^orders-office', TemplateView.as_view(template_name='management/order-office.html')),
   url(r'^order-department', TemplateView.as_view(template_name='management/order-department.html')),
   url(r'^customer-card', TemplateView.as_view(template_name='database/customer-card.html')),
   url(r'^order-graph', TemplateView.as_view(template_name='graphics/order.html')),
   url(r'^order-prod', TemplateView.as_view(template_name='production/order.html')),
   url(r'^order-inst', TemplateView.as_view(template_name='installation/order.html')),
   url(r'^offer', TemplateView.as_view(template_name='offer.html')),

   url(r'^add_update_note/$', 'office.views.add_update_note'),
)

custom_graphics_erp/office/models.py
# --*-- coding: utf-8 --*--

from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,
    Group)


class MyUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email,
                                password=password,
                                date_of_birth=date_of_birth
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    name = models.CharField(max_length=400)
    phone = models.CharField(max_length=40)
    date_of_birth = models.DateField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    group = models.ForeignKey(Group, blank=True, null=True)
    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):  # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class CompanyCategory(models.Model):
    title = models.CharField(max_length=200, verbose_name='name')

    def __unicode__(self):
        return self.title


class Company(models.Model):
    name = models.CharField(max_length=100, verbose_name='name', null=True, blank=True)
    email = models.EmailField(verbose_name='email', null=True, blank=True)
    phone = models.CharField(max_length=50, verbose_name='phone', null=True, blank=True)
    category = models.ForeignKey(CompanyCategory, verbose_name='category', related_name='category', null=True,
                                 blank=True)
    city = models.CharField(max_length=100, verbose_name='city', null=True, blank=True)
    website = models.CharField(max_length=200, verbose_name='website', null=True, blank=True)
    address = models.CharField(max_length=1000, verbose_name='address', null=True, blank=True)
    state = models.CharField(max_length=200, verbose_name='state', null=True, blank=True)
    post_code = models.CharField(max_length=200, verbose_name='Post Code', null=True, blank=True)
    description = models.TextField(verbose_name='description', null=True, blank=True)

    def __unicode__(self):
        return self.name

    def get_contact_person_list(self):
        return self.contactperson_set.all()

        # def get_request_list(self):
        # return self.company


class ContactPerson(models.Model):
    company = models.ForeignKey(Company)
    name = models.CharField(max_length=200, verbose_name='name', null=True, blank=True)
    email = models.EmailField(verbose_name='email', null=True, blank=True)
    phone = models.CharField(max_length=50, verbose_name='phone', null=True, blank=True)
    position = models.CharField(max_length=100, verbose_name='Position', null=True, blank=True)

    def __unicode__(self):
        return self.name


STATUS = (
    ('1', 'Need Quotation'),
    ('2', 'Quotation Sent'),
    ('3', 'Offer Declined'),
    ('4', 'New Order'),
    ('5', 'Design'),
    ('6', 'Production'),
    ('7', 'Installation'),
    ('8', 'Order Finished'),
    ('9', 'Archive Success'),
    ('10', 'Archive Fail'),
)


class Request(models.Model):
    contact_person = models.ForeignKey(ContactPerson, verbose_name='Contact Person', related_name='contact_person',
                                       null=True, blank=True)
    company = models.ForeignKey(Company, verbose_name='Company', related_name='company', null=True, blank=True)
    order_details = models.TextField(verbose_name='Order Details', null=True, blank=True)
    sending_date = models.DateTimeField(null=True, blank=True)
    price = models.IntegerField(verbose_name='Price', null=True, blank=True)
    payment = models.BooleanField(verbose_name='Payment', default=False)
    sent_invoice = models.BooleanField(default=False)
    sales_manager = models.ForeignKey(MyUser, related_name='sales_manager', null=True, blank=True)
    office_manager = models.ForeignKey(MyUser, related_name='office_manager', null=True, blank=True)
    graphics_user = models.ForeignKey(MyUser, related_name='graphics_user', null=True, blank=True)
    graphics_description = models.TextField(null=True, blank=True)
    graphics_min = models.IntegerField(null=True, blank=True)
    graphics_date_start = models.DateTimeField(null=True, blank=True)
    graphics_date_end = models.DateTimeField(null=True, blank=True)
    graphics_finish = models.BooleanField(default=False)
    installation_user = models.ForeignKey(MyUser, related_name='installation_user', null=True, blank=True)
    installation_description = models.TextField(null=True, blank=True)
    installation_date_start = models.DateTimeField(null=True, blank=True)
    installation_min = models.IntegerField(null=True, blank=True)
    installation_date_end = models.DateTimeField(null=True, blank=True)
    installation_finish = models.BooleanField(default=False)
    product_user = models.ForeignKey(MyUser, related_name='product_user', null=True, blank=True)
    product_description = models.TextField(null=True, blank=True)
    product_min = models.IntegerField(null=True, blank=True)
    product_date_start = models.DateTimeField(null=True, blank=True)
    product_date_end = models.DateTimeField(null=True, blank=True)
    product_finish = models.BooleanField(default=False)
    status = models.CharField(max_length=50, choices=STATUS, default='1')
    quotation_declined = models.TextField(null=True, blank=True)
    calculation_json = models.TextField(null=True, blank=True)


    def get_attachment_list(self):
        return self.attachment_set.all()


class Attachment(models.Model):
    request = models.ForeignKey(Request)
    attachment_file = models.FileField(upload_to='uploads/')

    def get_file_name(self):
        return self.attachment_file.name.split('/')[1]


class Organizer(models.Model):
    text = models.TextField()
    date = models.DateTimeField()
    user = models.ForeignKey(MyUser)


class AbstractModel(models.Model):
    title = models.CharField(max_length=200)
    value = models.FloatField()
    index_sort = models.IntegerField()

    class Meta:
        abstract = True
        ordering = ['index_sort', ]


class Material(AbstractModel):
    class Meta:
        verbose_name = 'material'
        verbose_name_plural = 'material'

    def __unicode__(self):
        return self.title


class Lamination(AbstractModel):
    class Meta:
        verbose_name = 'lamination'
        verbose_name_plural = 'lamination'

    def __unicode__(self):
        return self.title


class PlotPriceSam(AbstractModel):
    class Meta:
        verbose_name = 'Plot price sam'
        verbose_name_plural = 'Plot price sam'

    def __unicode__(self):
        return self.title


class CustomerType(models.Model):
    title = models.CharField(max_length=200)
    material = models.FloatField()
    tisk = models.FloatField()
    index_sort = models.IntegerField()


    class Meta:
        verbose_name = 'customer type'
        verbose_name_plural = 'customer type'

    def __unicode__(self):
        return self.title


class Print(AbstractModel):
    class Meta:
        verbose_name = 'print'
        verbose_name_plural = 'print'

    def __unicode__(self):
        return self.title


class Plot(AbstractModel):
    class Meta:
        verbose_name = 'plot'
        verbose_name_plural = 'plot'

    def __unicode__(self):
        return self.title


class SettingsContent(models.Model):
    """
        {% load get_keys %}
        {% get_keys 'kest' %}
    """
    title = models.CharField(max_length=300, verbose_name=u'Название')
    key = models.CharField(max_length=100, db_index=True, verbose_name=u'Ключ')

    image = models.ImageField(blank=True, null=True)
    is_image = models.BooleanField(default=False)
    text = models.TextField(blank=True, null=True)
    is_text = models.BooleanField(default=False)


    def get_value(self):
        if self.is_image:
            return self.image.url
        elif self.is_text:
            return self.text
        else:
            return ''

custom_graphics_erp/templates/sales/request_details.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    {% include 'includes/menu.html' %}
<section>
    <div class="request-for-sale container-fluid">

        <div class="row">
            <div class="col-lg-12">
                <h2 class="title">Request #{{ r.id }}</h2>
                <h2 class="sub-title">Description <a style="font-size: 16px" href="{% url "view_pdf" r.id%}" target="_blank">Show quotation</a></h2>
                <div class="col-lg-6">
                    <p>{{ r.order_details|linebreaksbr }}</p>
                </div>
                <div class="col-lg-2">
                    <p>Attachments</p>
                    <ol>
                        {%for elem in r.get_attachment_list%}
                            <li><a href="{{elem.attachment_file.url}}" target="_blank">{{ forloop.counter }}. {{elem.get_file_name}}</a></li>
                        {%endfor%}
                    </ol>
                </div>
            </div>
            <div class="col-lg-12 request-footer">
                <h2 class="sub-title">Customer contacts</h2>
                <div>
                    <p>Name:</p>
                    <span>{{r.contact_person.name}}</span>
                </div>
                <div>
                    <p>Address:</p>
                    <span>{{r.company.address}}</span>
                </div>
                <div>
                    <p>Mob/Email:</p>
                    <span>{{r.contact_person.phone}}{% if r.contact_person.email %}/{{r.contact_person.email}}{%endif%}</span>
                </div>
            </div>
            <div class="col-lg-12">
                {% if r.status == '3' %}
                    <p>{{ r.quotation_declined }}</p>
                {% else %}
                <span class="btn yellow" onclick='location.href="{% url "update-status" r.id %}?status=4&next=/sales/"'>Quotation Accepted</span>
                <span class="btn grey" data-target="#QuotationDeclined" data-toggle="modal">Quotation Declined</span>
                {% endif %}
            </div>
        </div>
    </div>

</section>
{% endblock %}
{% block modals %}
    <div class="modal fade" id="QuotationDeclined">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Quotation Declined</h4>
                </div>
                <div class="modal-body">
                    <form class="quotation-declined-form" action="." method="post">
                        {% csrf_token %}
                        <input type="hidden" name="date" id="id_date"/>
                        <input type="hidden" id="id_cell"/>
                        <div class="form-group">
                            <label for="message-text" class="control-label">Message:</label>
                            <textarea class="form-control textarea-note" name="message" id="id_note"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn grey" data-dismiss="modal">Close</button>
                    <button type="button" class="btn yellow save-message" >Save</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}

custom_graphics_erp/templates/sales/sales-index.html
{% extends 'base.html' %}
{% load future %}
{% load staticfiles %}

{% block content %}
    {% include 'includes/menu.html' %}
    <section>
        <div class="sales-list container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="title">Sales</h2>
                    <form role="form">
                        <div class="sales-table">
                            <div class="clear">
                                <h2 class="sub-title">Active sales</h2>
                                <a href="{% url 'add-request' %}" class="btn yellow plus-btn"><i>+</i>Add Request</a>
                            </div>
                            <table class="scrollable-table table w50">
                                <thead>
                                    <tr>
                                        <th>#Request</th>
                                        <th>Customer</th>
                                        <th>Status</th>
                                        <th>Sending date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in request_list %}
                                        <tr>
                                            <td class="{%if i.id in expired_list%}red-cell{%else%}{%endif%}"><a href="{% url "sales-details" i.id %}">#{{i.id}}</a></td>
                                            <td >{{i.company}}</td>
                                            <td class="success">{{i.get_status_display}}</td>
                                            <td>{{i.sending_date|date:"d.m.Y"}}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="table-calendar">
                            <h2 class="sub-title">Calendar</h2>
                            <table class="table">
                                <thead>
                                    <tr><th></th></tr>
                                </thead>
                                <tbody>
                                    {% for it in hours %}
                                        <tr>
                                            <td>{{ it|time:"h:i A" }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <div class="table-scroll sales-table" style="position: relative;">
                                <span class="next-table-cell next-week"><span class="glyphicon glyphicon-chevron-right next-week"></span></span>
                                <span class="previous-table-cell prev-week"><span class="glyphicon glyphicon-chevron-left prev-week"></span></span>
                                <table class="table">
                                    <thead>
                                        <tr>
                                            {% for d in days %}
                                                <th{% if d == today %} class="castom-class"{% endif %}>{{ d|date:"d.m.y" }}</th>
                                            {% endfor %}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for row in notes %}
                                        <tr>
                                            {% for cell in row %}
                                                <td>
                                                    {% if cell.2 %}
                                                    <p type="button" data-target="#newNote" data-toggle="modal" id="id_{{ cell.0|date:"dmY" }}{{ cell.1|time:"hiA" }}" onclick="init_add_note('{{ cell.0|date:"d.m.Y" }} {{ cell.1|time:"h:i A" }}', '{{ cell.2.text|linebreaksbr|escape }}', 'id_{{ cell.0|date:"dmY" }}{{ cell.1|time:"hiA" }}')">{{ cell.2.text }}</p>
                                                    <div class="tip">
                                                        <p>{{ cell.2.text|linebreaksbr }}</p>
                                                    </div>
                                                    {% else %}
                                                    <p type="button" data-target="#newNote" data-toggle="modal" data-dismiss="modal" id="id_{{ cell.0|date:"dmY" }}{{ cell.1|time:"hiA" }}" onclick="init_add_note('{{ cell.0|date:"d.m.Y" }} {{ cell.1|time:"h:i A" }}', '', 'id_{{ cell.0|date:"dmY" }}{{ cell.1|time:"hiA" }}')"></p>
                                                    {% endif %}
                                                </td>
                                            {% endfor %}
                                        </tr>
                                        {% endfor %}
{#                                        <tr>#}
{#                                            <td>#}
{#                                                <p>michael Jackson</p>#}
{#                                                <div class="tip">#}
{#                                                    <p class="tootle">Michael Jaclson</p>#}
{#                                                    <p><span>06.12.14</span> <span>12.00 AM</span></p>#}
{#                                                    <p>Need to call</p>#}
{#                                                </div>#}
{#                                            </td>#}
{#                                            <td>#}
{#                                                <p>Jeremi Jackson</p>#}
{#                                                <div class="tip">#}
{#                                                    <p class="tootle">Michael Jaclson</p>#}
{#                                                    <p><span>06.12.14</span> <span>12.00 AM</span></p>#}
{#                                                    <p>Need to call</p>#}
{#                                                </div>#}
{#                                            </td>#}
{#                                            {% for d in days %}#}
{#                                                <td><p>{{forloop.counter}}{{d}}</p></td>#}
{#                                            {% endfor %}#}
{#                                        </tr>#}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block modals %}
    <div class="modal fade" id="newNote">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">New note</h4>
                </div>
                <div class="modal-body">
                    <form>
                        {% csrf_token %}
                        <input type="hidden" name="date" id="id_date"/>
                        <input type="hidden" id="id_cell"/>
                        <div class="form-group">
                            <label for="message-text" class="control-label">Message:</label>
                            <textarea class="form-control textarea-note" name="note" id="id_note"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn grey" data-dismiss="modal">Close</button>
                    <button type="button" class="btn yellow" onclick="send_note()">Save</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/sales.js' %}"></script>
{% endblock %}